DROP USER DBHOPITAL CASCADE;

--1)
/*
DROP TABLESPACE tablespace [ INCLUDING CONTENTS [ {AND | KEEP} DATAFILES ] [ CASCADE CONSTRAINTS ] ] ; 
SQL> ALTER TABLESPACE data OFFLINE;	
SQL> DROP TABLESPACE data;	
SQL> DROP TABLESPACE data INCLUDING CONTENTS; 	
SQL> DROP TABLESPACE data INCLUDING CONTENTS CASCADE CONSTRAINTS;	
SQL> DROP TABLESPACE data INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
*/
DROP TABLESPACE HOPITAL_TBS INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE HOPITAL_TBS
DATAFILE 'C:\Users\Moflawer\Desktop\Dol_Gul_Dur\WorkShop_Tree\SQL\Almost_Done\TP_ASGBD\TP_ASGBD_1\htbs_datafile.dat'
SIZE 100M AUTOEXTEND ON;

DROP TABLESPACE HOPITAL_TempTBS INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TEMPORARY TABLESPACE HOPITAL_TempTBS
TEMPFILE 'C:\Users\Moflawer\Desktop\Dol_Gul_Dur\WorkShop_Tree\SQL\Almost_Done\TP_ASGBD\TP_ASGBD_1\htbs_tempfile.dat'
SIZE 100M AUTOEXTEND ON;

--2)
CREATE USER DBHOPITAL 
IDENTIFIED BY pwd
DEFAULT TABLESPACE HOPITAL_TBS
TEMPORARY TABLESPACE HOPITAL_TempTBS;

--3)
GRANT ALL PRIVILEGES TO DBHOPITAL;

--4)
/*
SERVICE (CODE-SERVICE, NOM-SERVICE, BATIMENT, DIRECTEUR*)
CHAMBRE (CODE-SERVICE*, NUM-CHAMBRE, SURVEILLANT*, NB_LITS)
EMPLOYE (NUM- EMP, NOM-EMP, PRENOM-EMP, ADRESSE-EMP, TEL-EMP)
MEDECIN (NUM- MED*, SPECIALITE)
INFIRMIER (NUM-INF*, CODE_SERVICE*, ROTATION, SALAIRE)
PATIENT (NUM-PATIENT, NOM-PATIENT, PRENOM-PATIENT, ADRESSE-PATIENT, TEL-PATIENT, MUTUELLE)
HOSPITALISATION (NUM-PATIENT*,  CODE_SERVICE*, NUM_CHAMBRE*, LIT)
SOIGNE (NUM-PATIENT*, NUM-MED*)
*/

--5)
connect DBHOPITAL/pwd;


CREATE TABLE EMPLOYE (
	NUM_EMP		 INTEGER,
	NOM_EMP		 VARCHAR2(50),
	PRENOM_EMP	 VARCHAR2(50),
	ADRESSE_EMP	 VARCHAR2(120),
	TEL_EMP		 VARCHAR2(20),
	CONSTRAINT PK_NUM_EMP PRIMARY KEY (NUM_EMP)
);

CREATE TABLE PATIENT (
	NUM_PATIENT	 INTEGER,
	NOM_PATIENT		 VARCHAR2(50),
	PRENOM_PATIENT	 VARCHAR2(50),
	ADRESSE_PATIENT	 VARCHAR2(120),
	TEL_PATIENT		 VARCHAR2(20),
	MUTUELLE 		 VARCHAR2(10),
	CONSTRAINT PK_NUM_PATIENT PRIMARY KEY (NUM_PATIENT)
);

CREATE TABLE MEDECIN (
	NUM_MED		 INTEGER,
	SPECIALITE 	 VARCHAR2(30),
	CONSTRAINT PK_NUM_MED PRIMARY KEY (NUM_MED),
	CONSTRAINT FK_NUM_MED FOREIGN KEY (NUM_MED)
	REFERENCES EMPLOYE (NUM_EMP),
	CONSTRAINT CHK_SPECIALITE CHECK (SPECIALITE IN (
	'Anesthesiste','Cardiologue','Generaliste',
	'Orthopediste','Radiologue','Traumatologue','Pneumologue'))
);

CREATE TABLE SOIGNE (
	NUM_PATIENT		 INTEGER,
	NUM_MED			 INTEGER,
	CONSTRAINT PK_NUM_PATIENT_MED PRIMARY KEY (NUM_PATIENT,NUM_MED),
	CONSTRAINT FK_NUM_PATIENT FOREIGN KEY (NUM_PATIENT)
	REFERENCES PATIENT (NUM_PATIENT),
	CONSTRAINT FK_NUM_MED_SOIGNE FOREIGN KEY (NUM_MED)
	REFERENCES MEDECIN (NUM_MED)
);

CREATE TABLE SERVICE (
	CODE_SERVICE	 VARCHAR2(20),
	NOM_SERVICE 	 VARCHAR2(50),
	BATIMENT		 VARCHAR2(10),
	DIRECTEUR 		 INTEGER,
	CONSTRAINT PK_CODE_SERVICE PRIMARY KEY (CODE_SERVICE),
	CONSTRAINT FK_DIRECTEUR FOREIGN KEY (DIRECTEUR)
	REFERENCES MEDECIN (NUM_MED),
	CONSTRAINT UNQ_NOM_SERVICE UNIQUE (NOM_SERVICE)
);

CREATE TABLE INFIRMIER (
	NUM_INF			 INTEGER,
	CODE_SERVICE 	 VARCHAR2(20),
	ROTATION		 VARCHAR2(15),
	SALAIRE 		 FLOAT,
	CONSTRAINT PK_NUM_INF PRIMARY KEY (NUM_INF),
	CONSTRAINT FK_NUM_INF FOREIGN KEY (NUM_INF)
	REFERENCES EMPLOYE (NUM_EMP),
	CONSTRAINT FK_CODE_SERVICE FOREIGN KEY (CODE_SERVICE)
	REFERENCES SERVICE (CODE_SERVICE),
	CONSTRAINT CHK_ROTATION CHECK (ROTATION IN ('JOUR','NUIT'))
);

CREATE TABLE CHAMBRE (
	CODE_SERVICE 	 VARCHAR2(20),
	NUM_CHAMBRE 	 INTEGER,
	SURVEILLANT		 INTEGER,
	NB_LITS			 INTEGER,
	CONSTRAINT PK_CODE_SERVIC_NUM_CHAMBRE PRIMARY KEY (CODE_SERVICE,NUM_CHAMBRE),
	CONSTRAINT FK_CODE_SERVICE_CHAMBRE FOREIGN KEY (CODE_SERVICE) 
	REFERENCES SERVICE (CODE_SERVICE),
	CONSTRAINT FK_SURVEILLANT FOREIGN KEY (SURVEILLANT)
	REFERENCES INFIRMIER (NUM_INF)
);

CREATE TABLE HOSPITALISATION (
	NUM_PATIENT 	 INTEGER,
	CODE_SERVICE 	 VARCHAR2(20),
	NUM_CHAMBRE 	 INTEGER,
	LIT				 INTEGER,
	CONSTRAINT PK_NUM_PATIENT_HOSPITALISATION PRIMARY KEY (NUM_PATIENT),
	CONSTRAINT FK_NUM_PATIENT_HOSPITALISATION FOREIGN KEY (NUM_PATIENT)
	REFERENCES PATIENT (NUM_PATIENT),
	CONSTRAINT FK_CODE_SERVICE_NUM_CHAMBRE FOREIGN KEY (CODE_SERVICE,NUM_CHAMBRE)
	REFERENCES CHAMBRE (CODE_SERVICE,NUM_CHAMBRE)
);

--Commandes DDL 
ALTER TABLE HOSPITALISATION
ADD DATE_HOST DATE ;

ALTER TABLE HOSPITALISATION 
DROP COLUMN DATE_HOST;

ALTER TABLE INFIRMIER
ADD CONSTRAINT NT_NLL_SALAIRE CHECK (SALAIRE IS NOT NULL);

ALTER TABLE PATIENT
ADD CONSTRAINT NT_NLL_MUTUELLE CHECK (MUTUELLE IS NOT NULL);

ALTER TABLE PATIENT 
MODIFY PRENOM_PATIENT VARCHAR2(100);

ALTER TABLE EMPLOYE
DROP COLUMN TEL_EMP;

ALTER TABLE EMPLOYE
ADD TEL_EMP VARCHAR2(15);

ALTER TABLE PATIENT 
RENAME COLUMN ADRESSE_PATIENT 
TO adr_pat;


ALTER TABLE PATIENT 
RENAME COLUMN adr_pat 
TO ADRESSE_PATIENT ;


ALTER TABLE INFIRMIER
ADD CONSTRAINT CHK_SALAIRE CHECK (SALAIRE BETWEEN 10000 AND 30000);

ALTER TABLE MEDECIN
ADD CONSTRAINT NT_NLL_SPECIALITE CHECK (SPECIALITE IS NOT NULL);


