	
/*==============================================================*/
/* SCRIPT : TP ORACLE 2                                          */
/*==============================================================*/

connect MEHDI/pwd

--1)
DROP USER ADMINHOPITAL CASCADE;

CREATE USER ADMINHOPITAL 
IDENTIFIED BY pwd;

--2)
connect ADMINHOPITAL/pwd;
/*
REMARQUE :  ERROR:
ORA-01045: user ADMINHOPITAL lacks CREATE SESSION privilege; logon denied
*/

connect MEHDI/pwd
--3)
GRANT CREATE SESSION TO ADMINHOPITAL ;

connect ADMINHOPITAL/pwd;

--4)
connect MEHDI/pwd;

GRANT CREATE TABLE , CREATE USER TO ADMINHOPITAL ;

Alter user ADMINHOPITAL QUOTA UNLIMITED ON HOPITAL_TBS;

SELECT privilege
FROM USER_SYS_PRIVS;

SELECT privilege
FROM SESSION_PRIVS;

--5)
connect ADMINHOPITAL/pwd;
SELECT * FROM DBHOPITAL.EMPLOYE;
/*
ERROR at line 1:
ORA-00942: table or view does not exist*/

--6)
connect DBHOPITAL/pwd;

GRANT SELECT ON EMPLOYE TO ADMINHOPITAL /*WITH ADMIN OPTION (privilège système)
										  WITH GRANT OPTION ;
										  
										  c'est commandes permette au bénificière
										  du privilège de le transmettre*/*/;

connect ADMINHOPITAL/pwd;

SELECT * FROM DBHOPITAL.EMPLOYE;

SELECT privilege FROM USER_TAB_PRIVS;


--7)
UPDATE DBHOPITAL.EMPLOYE
SET ADRESSE_EMP = '152, rue Hassiba Ben Bouali 2ème étage -HammaAlger'
WHERE NOM_EMP='ABDELMOUMEN'
AND   PRENOM_EMP='Nassima';
/*
ERROR at line 1:
ORA-01031: insufficient privileges*/

--8)
connect DBHOPITAL/pwd;

GRANT UPDATE ON EMPLOYE TO ADMINHOPITAL;

connect ADMINHOPITAL/pwd;

UPDATE DBHOPITAL.EMPLOYE
SET ADRESSE_EMP = '152, rue Hassiba Ben Bouali 2ème étage -HammaAlger'
WHERE NOM_EMP='ABDELMOUMEN'
AND   PRENOM_EMP='Nassima';

--9)
CREATE INDEX EMPLOYENOM_IX ON DBHOPITAL.EMPLOYE (NOM_EMP);
/*ERROR at line 1:
ORA-01031: insufficient privileges*/

--10)
connect DBHOPITAL/pwd;

GRANT  INDEX ON EMPLOYE TO ADMINHOPITAL;

connect ADMINHOPITAL/pwd

CREATE INDEX EMPLOYENOM_IX ON DBHOPITAL.EMPLOYE (NOM_EMP);
/*
ERROR at line 1:
ORA-01950: no privileges on tablespace 'SYSTEM'*/

--11)
/*
connect DBHOPITAL/pwd;

REVOKE CREATE SESSION,CREATE TABLE , CREATE USER FROM ADMINHOPITAL;
REVOKE SELECT ON EMPLOYE FROM ADMINHOPITAL;
REVOKE UPDATE ON EMPLOYE FROM ADMINHOPITAL;
REVOKE INDEX ON EMPLOYE FROM ADMINHOPITAL;

SELECT * FROM USER_SYS_PRIVS ;
SELECT * FROM USER_TAB_PRIVS;
*/
--12)
connect ADMINHOPITAL/pwd

--13)
connect MEHDI/pwd

DROP PROFILE ADMIN_PROFILE ;

CREATE PROFILE ADMIN_PROFILE LIMIT
	CPU_PER_CALL  		4000
	CONNECT_TIME 		50
	IDLE_TIME 30
	LOGICAL_READS_PER_CALL  1500
	PRIVATE_SGA 		20K
	FAILED_LOGIN_ATTEMPTS 3	
	PASSWORD_LIFE_TIME 60
	PASSWORD_REUSE_TIME 40
	PASSWORD_GRACE_TIME 5
	SESSIONS_PER_USER 	4	
	PASSWORD_REUSE_MAX UNLIMITED
	PASSWORD_LOCK_TIME 1;


--14)
ALTER USER ADMINHOPITAL PROFILE ADMIN_PROFILE;

--15)
DROP ROLE GESTIONNAIREPATIENT;

connect DBHOPITAL/pwd
CREATE ROLE GESTIONNAIREPATIENT ;

GRANT SELECT ON  PATIENT TO GESTIONNAIREPATIENT;
GRANT SELECT,UPDATE ON  HOSPITALISATION TO GESTIONNAIREPATIENT;
GRANT SELECT ON  SOIGNE TO GESTIONNAIREPATIENT;

--16)
GRANT GESTIONNAIREPATIENT TO ADMINHOPITAL;

GRANT CREATE SESSION TO ADMINHOPITAL
connect ADMINHOPITAL/pwd

SELECT * FROM DBHOPITAL.PATIENT;
SELECT * FROM DBHOPITAL.HOSPITALISATION;
SELECT * FROM DBHOPITAL.SOIGNE;
UPDATE DBHOPITAL.HOSPITALISATION 
SET    LIT = LIT ;

/*
Verifier QU	'un USER est connecté

 Vue : DBA_PROFILES*/













